import type { CSSProperties } from "react";

/** Co-located styles for the Project Context page. Layout mirrors the design
    mock: a narrow file-list panel flush against the sidebar and a wide
    preview pane — no page header, panes fill the full main-area height. */
export const s = {
  wrap: { display: "flex", alignItems: "stretch", height: "100%", minHeight: 0 } satisfies CSSProperties,

  filePanel: {
    width: 280,
    flexShrink: 0,
    borderRight: "1px solid var(--border)",
    display: "flex",
    flexDirection: "column",
    minHeight: 0,
  } satisfies CSSProperties,
  panelHead: { padding: "20px 18px 12px" } satisfies CSSProperties,
  panelLabel: {
    fontSize: 11,
    fontWeight: 700,
    letterSpacing: "0.09em",
    textTransform: "uppercase",
    color: "var(--text-muted)",
  } satisfies CSSProperties,
  panelRoot: {
    marginTop: 6,
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 12,
    color: "var(--text-secondary)",
    whiteSpace: "nowrap",
    overflow: "hidden",
    textOverflow: "ellipsis",
    direction: "rtl",
    textAlign: "left",
  } satisfies CSSProperties,
  toolbar: {
    display: "flex",
    alignItems: "center",
    gap: 2,
    padding: "2px 14px 10px",
    borderBottom: "1px solid var(--border)",
  } satisfies CSSProperties,

  fileList: {
    flex: 1,
    minHeight: 0,
    overflowY: "auto",
    padding: "4px 10px 16px",
    display: "flex",
    flexDirection: "column",
    gap: 2,
  } satisfies CSSProperties,
  fileRow: {
    display: "flex",
    alignItems: "center",
    gap: 8,
    width: "100%",
    padding: "7px 10px",
    borderRadius: 8,
    border: "none",
    background: "transparent",
    cursor: "pointer",
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 13,
    color: "var(--text-secondary)",
    textAlign: "left",
  } satisfies CSSProperties,
  fileRowActive: {
    background: "var(--bg-raised)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  fileName: {
    flex: 1,
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,

  previewPane: { flex: 1, minWidth: 0, display: "flex", flexDirection: "column", minHeight: 0 } satisfies CSSProperties,
  previewHead: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    gap: 16,
    padding: "20px 36px 10px",
  } satisfies CSSProperties,
  previewName: {
    fontFamily: "var(--font-mono, monospace)",
    fontSize: 14,
    fontWeight: 700,
    color: "var(--text-primary)",
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  previewUsedBy: {
    display: "flex",
    alignItems: "center",
    gap: 7,
    fontSize: 12.5,
    color: "var(--text-secondary)",
    flexShrink: 0,
  } satisfies CSSProperties,
  previewBody: { flex: 1, minHeight: 0, overflowY: "auto", padding: "8px 36px 56px" } satisfies CSSProperties,
  previewContent: { maxWidth: 860, fontSize: 13.5 } satisfies CSSProperties,
  previewEmpty: {
    flex: 1,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    fontSize: 13,
    color: "var(--text-muted)",
  } satisfies CSSProperties,

  panelState: { padding: "8px 18px" } satisfies CSSProperties,

  headLeft: { display: "flex", alignItems: "center", gap: 14, minWidth: 0 } satisfies CSSProperties,
  seg: {
    display: "inline-flex",
    background: "var(--bg-raised)",
    border: "1px solid var(--border)",
    borderRadius: 8,
    padding: 2,
    flexShrink: 0,
  } satisfies CSSProperties,
  segBtn: {
    border: "none",
    background: "transparent",
    color: "var(--text-muted)",
    fontSize: 12,
    fontWeight: 600,
    padding: "4px 14px",
    borderRadius: 6,
    cursor: "pointer",
  } satisfies CSSProperties,
  segBtnActive: {
    background: "var(--bg-elevated)",
    color: "var(--text-primary)",
  } satisfies CSSProperties,
  headRight: { display: "flex", alignItems: "center", gap: 14, flexShrink: 0 } satisfies CSSProperties,
  editActions: { display: "flex", gap: 8, marginTop: 12, justifyContent: "flex-end" } satisfies CSSProperties,
  modalError: { color: "var(--crit)", fontSize: 12.5, marginTop: 8 } satisfies CSSProperties,
} as const;
