import type { CSSProperties } from "react";

/** Co-located styles for EvalsTab. */
export const s = {
  wrap: { maxWidth: 920 } satisfies CSSProperties,
  metricsLabel: {
    display: "flex",
    alignItems: "center",
    gap: 6,
    marginBottom: 12,
  } satisfies CSSProperties,
  metricsLabelText: {
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.05em",
    color: "var(--text-secondary)",
  } satisfies CSSProperties,
  headerActions: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  metricsGrid: {
    display: "flex",
    gap: 12,
    marginBottom: 24,
  } satisfies CSSProperties,
  casesHeader: {
    display: "flex",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  } satisfies CSSProperties,
  casesHeaderLeft: { display: "flex", alignItems: "center", gap: 12 } satisfies CSSProperties,
  h3: { fontSize: 15, fontWeight: 700 } satisfies CSSProperties,
  passingCounter: { fontSize: 13, color: "var(--text-secondary)" } satisfies CSSProperties,
  list: { display: "flex", flexDirection: "column", gap: 8 } satisfies CSSProperties,
  row: {
    display: "flex",
    alignItems: "center",
    gap: 12,
    padding: "11px 14px",
    borderRadius: 8,
    border: "1px solid var(--border)",
    background: "var(--bg-elevated)",
  } satisfies CSSProperties,
  rowMain: { display: "flex", flexDirection: "column", gap: 4, flex: 1, minWidth: 0 } satisfies CSSProperties,
  rowNameLine: { display: "flex", alignItems: "center", gap: 8 } satisfies CSSProperties,
  name: {
    fontSize: 14,
    fontWeight: 600,
    color: "var(--text-primary)",
    minWidth: 0,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  } satisfies CSSProperties,
  rowMeta: { display: "flex", alignItems: "center", gap: 10 } satisfies CSSProperties,
  rowActions: { display: "flex", alignItems: "center", gap: 6, flexShrink: 0 } satisfies CSSProperties,
  statusBadge: (color: string, bg: string): CSSProperties => ({
    display: "inline-flex",
    alignItems: "center",
    padding: "2px 9px",
    borderRadius: 999,
    fontSize: 11,
    fontWeight: 700,
    textTransform: "uppercase",
    letterSpacing: "0.03em",
    color,
    background: bg,
  }),
  deleteModalBody: { fontSize: 14, color: "var(--text-secondary)", padding: "20px 24px" } satisfies CSSProperties,
  deleteModalFooter: { display: "flex", justifyContent: "flex-end", gap: 8 } satisfies CSSProperties,
} as const;
